Restrict python-jsonschema for testing
There is incompatibility in jsonschema 2.6 that cause
ImportError: No module named functools32

That also include port of stacksorge/tasklib
(see ebcb20a96c7a44494b161569d13d6d74ad3109da)

Change-Id: I8c86e897a6d693e4bc9e5c57006ce71b6bad40d2
Closes-Bug: #1662168
Closes-Bug: #1507208