Restrict python-jsonscema for testing
There is incompatibility in jsonschema 2.6 that cause
ImportError: No module named functools32

Change-Id: I8c86e897a6d693e4bc9e5c57006ce71b6bad40d2
Closes-Bug: #1662168