Keep manifests ASCII-only (to support ruby >= 1.9)
Replace unicode characters in comments with their ASCII equivalents. Fixes
deployment failure with ruby >= 1.9 (which is picky about character encoding):

~# LC_ALL=C puppet apply /etc/puppet/manifests/site.pp 2>&1 | grep Error
Error: invalid byte sequence in US-ASCII at
/etc/puppet/modules/horizon/manifests/init.pp:1 on node node-1.local
Wrapped exception:
invalid byte sequence in US-ASCII
Error: invalid byte sequence in US-ASCII at
/etc/puppet/modules/horizon/manifests/init.pp:1 on node node-1.local

Change-Id: I3618a3fd136af0151162235f0b6888aef2593e52